### ISSUE TITLE
Criar índice para o projeto Best Practices

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plugins-idx#1]
Nome do índice: `best-practices`

Lista inicial de campos:
- ID (não repetitivo, pesquisável, armazenado)
- title (não repetitivo, pesquisável, armazenado, busca livre)
- introduction (não repetitivo, pesquisável, armazenado, busca livre)
- objectives (não repetitivo, pesquisável, armazenado)
- activities (não repetitivo, pesquisável, armazenado)
- main_results (não repetitivo, pesquisável, armazenado)
- factors (não repetitivo, pesquisável, armazenado)
- outcome_information (não repetitivo, não pesquisável, armazenado)
- describe_how (não repetitivo, não pesquisável, armazenado)
- challenges_information (não repetitivo, não pesquisável, armazenado)
- lessons_information (não repetitivo, não pesquisável, armazenado)
- country (não repetitivo, pesquisável, armazenado)
- subregion (não repetitivo, pesquisável, armazenado)
- target (repetitivo, pesquisável, armazenado)
- start_date (não repetitivo, não pesquisável, armazenado)
- end_date (não repetitivo, não pesquisável, armazenado)

**Comment by viniciusandrade** [comment]
@wilsonmoura OK, estou criando a instância para o índice. 

Poderia, por favor, editar seu comentário e ao lado de cada campo informar:

- se é repetitivo
- se deve ser pesquisável 
- se deve ser armazenado para display
- se deve fazer parte da busca livre
 
Exemplo:

- title (não repetitivo, pesquisável, armazenado, busca livre)
...
- start_date (não repetitivo, não pesquisável, armazenado)

Obrigado

**Comment by wilsonmoura** [comment]
@viniciusandrade descrição atualizada conforme solicitado.

**Comment by viniciusandrade** [comment]
@wilsonmoura instância criada com as definições de campos informadas.

Este é o endpoint:
http://plugins-idx.bvsalud.org:8983/solr/best-practices/

Exemplo de chamada para o método de busca:
http://plugins-idx.bvsalud.org:8983/solr/best-practices/select?q=*%3A*&wt=json&indent=true

**Comment by wilsonmoura** [comment]
@viniciusandrade favor incluir mais alguns campos:
- type (não repetitivo, pesquisável, armazenado)
- population_group (não repetitivo, pesquisável, armazenado)
- stakeholder (não repetitivo, pesquisável, armazenado)
- institution (não repetitivo, pesquisável, armazenado)
- intervention (repetitivo, pesquisável, armazenado)

**Comment by wilsonmoura** [comment]
@viniciusandrade favor incluir mais alguns campos:
- type (não repetitivo, pesquisável, armazenado)
- population_group (não repetitivo, pesquisável, armazenado)
- stakeholder (não repetitivo, pesquisável, armazenado)
- institution (não repetitivo, pesquisável, armazenado)
- intervention (repetitivo, pesquisável, armazenado)

**Comment by viniciusandrade** [comment]
@wilsonmoura campos adicionados no schema, favor verificar.

**Comment by wilsonmoura** [comment]
@viniciusandrade está tudo OK. Obrigado.

**Comment by wilsonmoura** [comment]
@viniciusandrade favor atualizar atributos do seguinte campo:

- population_group (repetitivo, pesquisável, armazenado)

**Comment by viniciusandrade** [comment]
@wilsonmoura ajuste realizado e ambiente de teste/produção atualizados.

**Comment by wilsonmoura** [comment]
@viniciusandrade favor incluir mais alguns campos:
- entity (repetitivo, pesquisável, armazenado)
- technical_matter (repetitivo, pesquisável, armazenado)

Favor também atualizar atributos dos seguintes campos:
- subregion (repetitivo, pesquisável, armazenado)
- country (repetitivo, pesquisável, armazenado)
- stakeholder (repetitivo, pesquisável, armazenado)

**Comment by viniciusandrade** [comment]
@wilsonmoura ajustes disponíveis no ambiente de testes. Favor validar.

**Comment by wilsonmoura** [comment]
@viniciusandrade está tudo OK. Obrigado.

**Comment by wilsonmoura** [comment]
Incluir o campo abaixo no índice:
- outcomes (não repetitivo, pesquisável, armazenado)

**Comment by wilsonmoura** [comment]
@viniciusandrade favor atualizar o índice no ambiente de testes e produção.

**Comment by viniciusandrade** [comment]
@wilsonmoura ambientes atualizados.

**Comment by wilsonmoura** [comment]
Incluir mais alguns campos:
- keywords (repetitivo, pesquisável, armazenado)
- sustainability (não repetitivo, pesquisável, armazenado)
- coop_modality (não repetitivo, pesquisável, armazenado)

**Comment by wilsonmoura** [comment]
@viniciusandrade favor atualizar novamente o índice no ambiente de testes e produção.

**Comment by wilsonmoura** [comment]
Incluir o campo abaixo no índice:
- call (não repetitivo, pesquisável, armazenado)

**Comment by wilsonmoura** [comment]
@viniciusandrade favor atualizar novamente o índice no ambiente de testes e produção.

**Comment by wilsonmoura** [comment]
@viniciusandrade favor incluir o campo abaixo no índice:

- is_private (não repetitivo, pesquisável)

**Comment by viniciusandrade** [comment]
@wilsonmoura campo criado e disponível nos ambientes de teste e prod :+1:

**Comment by wilsonmoura** [comment]
@viniciusandrade favor ajustar os atributos do campo abaixo no índice:

- is_private (não repetitivo, pesquisável, armazenado)

**Comment by viniciusandrade** [comment]
@wilsonmoura ajuste realizado e aplicado nos ambientes.
