### ISSUE TITLE
Criar clusters no índice do projeto Best Practices

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plugins-idx#3]
Lista inicial de clusters:
- country
- subregion
- target

**Comment by viniciusandrade** [comment]
@wilsonmoura fiz os ajustes no ambiente de testes mas preciso que você faça a reindexação dos documentos de lá ou a criação de novos para verificar se os valores irão aparecer nos clusters.

**Comment by viniciusandrade** [comment]
@wilsonmoura encontrei um pequeno problema na configuração e realizei o ajuste no ambiente de testes, enviei alguns documentos de teste e agora parece que os clusters estão sendo calculados. Favor reindexar para validar. 

Obrigado

**Comment by wilsonmoura** [comment]
@viniciusandrade realizei a reindexação e parece que agora funcionou. Favor incluir mais alguns clusters:
- type
- intervention
- population_group
- institution
- stakeholder

**Comment by viniciusandrade** [comment]
@wilsonmoura clusters adicionados na configuração, favor verificar.

**Comment by wilsonmoura** [comment]
@viniciusandrade está tudo OK. Obrigado.

**Comment by wilsonmoura** [comment]
@viniciusandrade Favor incluir o seguinte cluster:
- entity

**Comment by wilsonmoura** [comment]
Incluir o cluster abaixo no índice:
- outcomes

**Comment by wilsonmoura** [comment]
@viniciusandrade favor atualizar o índice no ambiente de testes e produção.

**Comment by viniciusandrade** [comment]
@wilsonmoura ambientes atualizados.

**Comment by wilsonmoura** [comment]
Incluir o cluster abaixo no índice:
- call

**Comment by wilsonmoura** [comment]
@viniciusandrade favor atualizar novamente o índice no ambiente de testes e produção.

**Comment by viniciusandrade** [comment]
@wilsonmoura ambientes de teste e produção atualizados.

**Comment by wilsonmoura** [comment]
@viniciusandrade favor Incluir o cluster abaixo no índice:

- is_private

**Comment by viniciusandrade** [comment]
@wilsonmoura cluster adicionado na lista e configuração dos ambientes de teste e produção atualizados.
