### ISSUE TITLE
Incluir campos no índice do projeto Relatos de Experiência

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plugins-idx#4]
Lista de campos:
- ID (não repetitivo, pesquisável, armazenado)
- title (não repetitivo, pesquisável, armazenado, busca livre)
- notes (não repetitivo, pesquisável, armazenado, busca livre)
- issue (não repetitivo, pesquisável, armazenado, busca livre)
- status (não repetitivo, pesquisável, armazenado)
- other_status (não repetitivo, pesquisável, armazenado)
- objectives (não repetitivo, pesquisável, armazenado)
- resources (não repetitivo, pesquisável, armazenado)
- context (não repetitivo, pesquisável, armazenado)
- main_results (não repetitivo, pesquisável, armazenado)
- challenges_information (não repetitivo, não pesquisável, armazenado)
- other_results (não repetitivo, pesquisável, armazenado)
- lessons_learned (não repetitivo, pesquisável, armazenado)
- other_medias (não repetitivo, pesquisável, armazenado)
- products_information (não repetitivo, não pesquisável, armazenado)
- start_date (não repetitivo, não pesquisável, armazenado)
- end_date (não repetitivo, não pesquisável, armazenado)
- partial_date (não repetitivo, não pesquisável, armazenado)
- keywords (repetitivo, pesquisável, armazenado)
- thematic_area (repetitivo, pesquisável, armazenado)
- population_group (repetitivo, pesquisável, armazenado)
- other_population_group (não repetitivo, pesquisável, armazenado)

**Comment by viniciusandrade** [comment]
@wilsonmoura ajustes disponíveis no ambiente de testes. Favor validar.

**Comment by wilsonmoura** [comment]
@viniciusandrade favor incluir mais um campo no índice:
- other_date (não repetitivo, pesquisável, armazenado)

Favor também revisar a configuração do campo abaixo:
- other_population_group (não repetitivo, pesquisável, armazenado)

**Comment by viniciusandrade** [comment]
@wilsonmoura ajustes realizados, favor realizar novo teste.

**Comment by wilsonmoura** [comment]
@viniciusandrade está tudo OK. Obrigado!

**Comment by wilsonmoura** [comment]
@viniciusandrade favor incluir mais alguns campos no índice:
- description (não repetitivo, pesquisável, armazenado, busca livre)
- fulltext (não repetitivo, pesquisável, armazenado, busca livre)
- country (não repetitivo, pesquisável, armazenado)
- collection (repetitivo, pesquisável, armazenado)
- descriptors (repetitivo, pesquisável, armazenado)
- other_docs (não repetitivo, não pesquisável, armazenado)
- other_videos (não repetitivo, não pesquisável, armazenado)

Favor também revisar a configuração do campo abaixo:
- other_medias (não repetitivo, não pesquisável, armazenado)

**Comment by wilsonmoura** [comment]
@viniciusandrade favor incluir mais alguns campos no índice:
- description (não repetitivo, pesquisável, armazenado, busca livre)
- fulltext (não repetitivo, pesquisável, armazenado, busca livre)
- country (não repetitivo, pesquisável, armazenado)
- collection (repetitivo, pesquisável, armazenado)
- descriptors (repetitivo, pesquisável, armazenado)
- other_docs (não repetitivo, não pesquisável, armazenado)
- other_videos (não repetitivo, não pesquisável, armazenado)
- related_links (não repetitivo, não pesquisável, armazenado)

Favor também revisar a configuração do campo abaixo:
- other_medias (não repetitivo, não pesquisável, armazenado)

**Comment by wilsonmoura** [comment]
@viniciusandrade favor incluir mais alguns campos no índice:
- description (não repetitivo, pesquisável, armazenado, busca livre)
- fulltext (não repetitivo, pesquisável, armazenado, busca livre)
- region (não repetitivo, pesquisável, armazenado)
- city (não repetitivo, pesquisável, armazenado)
- country (não repetitivo, pesquisável, armazenado)
- collection (repetitivo, pesquisável, armazenado)
- descriptors (repetitivo, pesquisável, armazenado)
- other_docs (não repetitivo, não pesquisável, armazenado)
- other_videos (não repetitivo, não pesquisável, armazenado)
- related_links (não repetitivo, não pesquisável, armazenado)

Favor também revisar a configuração do campo abaixo:
- other_medias (não repetitivo, não pesquisável, armazenado)

**Comment by viniciusandrade** [comment]
@wilsonmoura campos incluídos no ambiente de teste. Favor validar e informar se já podemos aplicar em produção.

**Comment by wilsonmoura** [comment]
@viniciusandrade está tudo OK. Obrigado!

**Comment by wilsonmoura** [comment]
@viniciusandrade está tudo OK. Já pode aplicar em produção. Obrigado!
