### ISSUE TITLE
Criar clusters no índice do projeto Relatos de Experiência

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plugins-idx#5]
Lista de clusters:
- population_group
- thematic_area

**Comment by viniciusandrade** [comment]
@wilsonmoura ajustes disponíveis no ambiente de testes. Favor validar.

**Comment by wilsonmoura** [comment]
@viniciusandrade fiz um teste e parece que os clusters não estão sendo populados. Para acessar o documento que publicamos nesse teste, basta acessar https://bestpractices.teste.bvsalud.org/relatos/

**Comment by viniciusandrade** [comment]
@wilsonmoura ajustes realizados, favor realizar novo teste.

**Comment by wilsonmoura** [comment]
@viniciusandrade está tudo OK. Obrigado.

**Comment by wilsonmoura** [comment]
@viniciusandrade Favor incluir mais alguns clusters:
- country
- collection

**Comment by viniciusandrade** [comment]
@wilsonmoura campos incluídos no ambiente de teste. Favor validar e informar se já podemos aplicar em produção.

**Comment by wilsonmoura** [comment]
@viniciusandrade favor ajustar o atributo **type** de `text` para `string` nos campos abaixo:
- country
- collection

**Comment by wilsonmoura** [comment]
@viniciusandrade ajustes realizados. Favor atualizar o índice no servidor.

**Comment by viniciusandrade** [comment]
@wilsonmoura atualizado nos ambientes de testes e produção.
